version: '3'
services:
    acme.sh:
        image: neilpang/acme.sh
        restart: always
        volumes:
            - "./out:/acme.sh:z"
        environment:
            - CF_Key="c02a218f0154d12399b1fd536125a848cd62f"
            - CF_Email="1009371162@qq.com"
        command: daemon
    x-ui:
        image: srcrs/x-ui
        restart: always
        network_mode: "host"
        volumes:
            - "./out:/root/out"
        command:
            - /bin/bash
            - -c
            - |
                x-ui start
                sleep infinity
